// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef tc_wbarconf_h
#define tc_wbarconf_h
#include <FL/Fl.H>
void genConf();
void brwWbarCB(Fl_Widget *, void *);
void brwXlistCB(Fl_Widget *, void *);
void btnApplyCB(Fl_Widget *, void *);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Group.H>
extern Fl_Group *grpGUI;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brwWbar;
extern Fl_Browser *brwXlist;
#include <FL/Fl_Choice.H>
extern Fl_Choice *posChoice;
#include <FL/Fl_Slider.H>
extern Fl_Slider *isizeChoice;
extern Fl_Slider *zoomChoice;
#include <FL/Fl_Button.H>
extern Fl_Group *grpOptions;
#include <FL/Fl_Output.H>
extern Fl_Output *txtFromGUI;
extern Fl_Browser *brwOptions;
#include <FL/Fl_Input.H>
extern Fl_Input *txtOptions;
extern Fl_Menu_Item menu_posChoice[];
#endif
