// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef tcemirror_h
#define tcemirror_h
#include <FL/Fl.H>
void btnCallback(Fl_Widget*, void* userdata);
void mirrorBrwCallback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *urlInput;
#include <FL/Fl_Browser.H>
extern Fl_Browser *mirrorBrw;
#include <FL/Fl_Button.H>
#endif
