// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef tcemirror_h
#define tcemirror_h
#include <FL/Fl.H>
void btnCallback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *urlInput;
extern Fl_Input *protocolInput;
extern Fl_Input *repositoryInput;
#include <FL/Fl_Button.H>
#endif
