// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef appbrowser_h
#define appbrowser_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
extern Fl_Choice *search_choices;
#include <FL/Fl_Input.H>
extern Fl_Input *search_field;
#include <FL/Fl_Box.H>
extern Fl_Box *box_select;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brw_select;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs;
#include <FL/Fl_Group.H>
extern Fl_Group *tab_info;
extern Fl_Browser *brw_info;
extern Fl_Group *tab_files;
extern Fl_Browser *brw_list;
extern Fl_Group *tab_depends;
extern Fl_Browser *brw_dep;
extern Fl_Group *tab_size;
extern Fl_Browser *brw_size;
extern Fl_Choice *install_choices;
extern Fl_Button *btn_go;
#include <FL/Fl_Output.H>
extern Fl_Output *status_out;
extern Fl_Menu_Item menu_search_choices[];
extern Fl_Menu_Item menu_install_choices[];
#endif
