// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef appbrowser_h
#define appbrowser_h
#include <FL/Fl.H>
void btn_callback(Fl_Widget *, void* userdata);
void brw_extn_callback(Fl_Widget *, void *);
void local_btn_callback(Fl_Widget*, void* userdata);
void tabs_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
extern void btn_callback(Fl_Menu_*, void*);
extern void local_btn_callback(Fl_Menu_*, void*);
#include <FL/Fl_Box.H>
extern Fl_Box *box_extensions;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brw_extn;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs;
#include <FL/Fl_Group.H>
extern Fl_Group *tab_info;
extern Fl_Browser *brw_info;
extern Fl_Group *tab_files;
extern Fl_Browser *brw_list;
extern Fl_Group *tab_depends;
extern Fl_Browser *brw_dep;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_install;
extern Fl_Button *btn_download;
#include <FL/Fl_Input.H>
extern Fl_Input *search_field;
extern Fl_Menu_Item menu_[];
#endif
