// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include <libintl.h>
#include "wbarconf.h"
// (c) Robert Shingledecker 2010
// Zoom, Icon Size, Icon Text options - Brian Smith
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <FL/fl_message.H>
#include <FL/Fl_File_Chooser.H>
#include <locale.h>
using namespace std;
static string home, tcedir, command, selected; 
static int chosen,results; 
static string onbootList, wbarXlist, options; 
static string wbarIcons = "/usr/local/tce.icons"; 

void brw_wbar_callback(Fl_Widget *, void *) {
  if (brw_wbar->value())
{
   chosen = brw_wbar->value();
   selected = brw_wbar->text(chosen);
   command = "wbar_mv_icon " + selected.substr(0,selected.length()-1) + " " + wbarIcons + " " + wbarXlist;
   system(command.c_str());
   brw_wbarXlist->add(selected.c_str());
   brw_wbar->remove(chosen);
//   command = "wbar.sh";
//   system(command.c_str());
}
}

void brw_wbarXlist_callback(Fl_Widget *, void *) {
  if (brw_wbarXlist->value())
{
   chosen = brw_wbarXlist->value();
   selected = brw_wbarXlist->text(chosen);
   command = "wbar_mv_icon " + selected.substr(0,selected.length()-1) + " " + wbarXlist + " " + wbarIcons;
   system(command.c_str());
   brw_wbarXlist->remove(chosen);
   brw_wbar->add(selected.c_str());
//   command = "wbar.sh";
//   system(command.c_str());
}
}

void btnApplyCB(Fl_Widget *, void *) {
  options = "-bpress ";
int pos = posChoice->value();
switch(pos)
{
   case 0  : options += "-p top";
             break;;
   case 1  : options += "-p bottom";
             break;;
   case 2  : options += "-p left -vbar";
             break;;
   case 3  : options += "-p right -vbar";
             break;;
   default : options += "-p bottom";
             break;;
}
double zoomf_value = zoomChoice->value();
if (zoomf_value == 1) {zoomf_value = 1.00001;}
string zoomf;
ostringstream stream;
stream << (double)zoomf_value;
zoomf = stream.str();
options += " -zoomf " + zoomf;

stream.str("");
string isize;
stream << (double)isizeChoice->value();
isize = stream.str();
options += " -isize " + isize;

if (textChoice->value() == 0) {options += " -nofont";}


string fname = home + "/.wbar";
ofstream fout(fname.c_str(), ios::out|ios::out);
if (! fout.is_open())
{
   cerr << "Can't open .wbar for output." << endl;
   exit(EXIT_FAILURE);
}
fout << options << endl;
fout.close();

command = "wbar.sh";
system(command.c_str());
}

Fl_Double_Window *window=(Fl_Double_Window *)0;

Fl_Browser *brw_wbar=(Fl_Browser *)0;

Fl_Browser *brw_wbarXlist=(Fl_Browser *)0;

Fl_Choice *posChoice=(Fl_Choice *)0;

Fl_Menu_Item menu_posChoice[] = {
 {gettext("Top"), 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {gettext("Bottom"), 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {gettext("Left"), 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {gettext("Right"), 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Slider *zoomChoice=(Fl_Slider *)0;

Fl_Slider *isizeChoice=(Fl_Slider *)0;

Fl_Check_Button *textChoice=(Fl_Check_Button *)0;

int main(int argc, char **argv) {
  setlocale(LC_ALL, "");
bindtextdomain("tinycore","/usr/local/share/locale");
textdomain("tinycore");
  { window = new Fl_Double_Window(420, 385, gettext("eXclude Wbar Icons"));
    { brw_wbar = new Fl_Browser(5, 20, 200, 265, gettext("Wbar Icons"));
      brw_wbar->type(1);
      brw_wbar->textfont(4);
      brw_wbar->callback((Fl_Callback*)brw_wbar_callback);
      brw_wbar->align(FL_ALIGN_TOP);
    } // Fl_Browser* brw_wbar
    { brw_wbarXlist = new Fl_Browser(215, 20, 200, 265, gettext("eXcluded Items"));
      brw_wbarXlist->type(1);
      brw_wbarXlist->textfont(4);
      brw_wbarXlist->callback((Fl_Callback*)brw_wbarXlist_callback);
      brw_wbarXlist->align(FL_ALIGN_TOP);
    } // Fl_Browser* brw_wbarXlist
    { posChoice = new Fl_Choice(100, 290, 85, 20, gettext("Wbar Position"));
      posChoice->down_box(FL_BORDER_BOX);
      posChoice->menu(menu_posChoice);
      posChoice->value(1);
    } // Fl_Choice* posChoice
    { Fl_Button* o = new Fl_Button(165, 350, 80, 25, gettext("Apply"));
      o->callback((Fl_Callback*)btnApplyCB);
    } // Fl_Button* o
    { zoomChoice = new Fl_Slider(305, 320, 105, 20, gettext("Wbar Zoom"));
      zoomChoice->type(1);
      zoomChoice->minimum(1);
      zoomChoice->maximum(3);
      zoomChoice->step(0.1);
      zoomChoice->value(2);
      zoomChoice->align(FL_ALIGN_LEFT);
    } // Fl_Slider* zoomChoice
    { isizeChoice = new Fl_Slider(305, 290, 105, 20, gettext("Wbar Icon Size"));
      isizeChoice->type(1);
      isizeChoice->minimum(10);
      isizeChoice->maximum(80);
      isizeChoice->step(1);
      isizeChoice->value(32);
      isizeChoice->align(FL_ALIGN_LEFT);
    } // Fl_Slider* isizeChoice
    { textChoice = new Fl_Check_Button(165, 320, 25, 20, gettext("Wbar Text Labels"));
      textChoice->down_box(FL_DOWN_BOX);
      textChoice->align(FL_ALIGN_LEFT);
    } // Fl_Check_Button* textChoice
    window->size_range(1, 0, 3, 0);
    window->end();
    window->resizable(window);
  } // Fl_Double_Window* window
  FILE* run = popen("zoomf=`cat ~/.wbar` && zoomf=${zoomf##*zoomf} && echo $zoomf | awk '{print $1}'", "r");
char b[10];
fscanf(run, "%s", b);
pclose(run);
double zoomf = atof(b);
if (zoomf == 0) { zoomf = 2.0; }
zoomChoice->value(zoomf);

run = popen("isize=`cat ~/.wbar` && isize=${isize##*isize} && echo $isize | awk '{print $1}'", "r");
char b2[10];
fscanf(run, "%s", b2);
pclose(run);
double isize = atof(b2);
if (isize == 0) { isize = 32.0; }
isizeChoice->value(isize);

int rc = system("cat ~/.wbar | grep nofont >/dev/null 2>&1");
if (rc == 0){ textChoice->value(0);} else {textChoice->value(1);}

home = getenv("HOME");
ifstream tcedir_file("/opt/.tce_dir");
getline(tcedir_file,tcedir);
tcedir_file.close();
wbarXlist = tcedir + "/xwbar.lst";

command = "awk '/t: /{if (NR>4)print $2}' < " + wbarIcons;
FILE *pipe = popen(command.c_str(),"r");
char *mbuf = (char *) calloc(PATH_MAX,sizeof(char));

if (pipe) {
  brw_wbar->clear();
  while (fgets(mbuf,PATH_MAX,pipe)) {
     string line(mbuf);
     brw_wbar->add(line.c_str());
     Fl::flush();
   }
   pclose(pipe);
   free(mbuf);
}

command = "awk '/t: /{print $2}' < " + wbarXlist + " 2>/dev/null";
pipe = popen(command.c_str(),"r");
mbuf = (char *) calloc(PATH_MAX,sizeof(char));

if (pipe) {
  brw_wbarXlist->clear();
  while (fgets(mbuf,PATH_MAX,pipe)) {
     string line(mbuf);
     brw_wbarXlist->add(line.c_str());
     Fl::flush();
   }
   pclose(pipe);
   free(mbuf);
}
  window->show(argc, argv);
  return Fl::run();
}
