// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef wbarconf_h
#define wbarconf_h
#include <FL/Fl.H>
void brw_wbar_callback(Fl_Widget *, void *);
void brw_wbarXlist_callback(Fl_Widget *, void *);
void btnApplyCB(Fl_Widget *, void *);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brw_wbar;
extern Fl_Browser *brw_wbarXlist;
#include <FL/Fl_Choice.H>
extern Fl_Choice *posChoice;
#include <FL/Fl_Button.H>
#include <FL/Fl_Slider.H>
extern Fl_Slider *zoomChoice;
extern Fl_Slider *isizeChoice;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *textChoice;
extern Fl_Menu_Item menu_posChoice[];
#endif
