// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef tc_grub4dos_h
#define tc_grub4dos_h
#include <FL/Fl.H>
#include <unistd.h>
void cursor_normal();
void cursor_wait();
void selectFile();
void prepTarget();
void btnCB(Fl_Widget*, void*userdata);
void btnProceedCB(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *wWizard;
#include <FL/Fl_Group.H>
extern Fl_Group *grpType;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btnMicro;
extern Fl_Check_Button *btnTiny;
#include <FL/Fl_Output.H>
extern Fl_Output *fullpathOutput;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brwTarget;
extern Fl_Group *grpFormat;
extern Fl_Group *FormatType;
#include <FL/Fl_Round_Button.H>
extern Fl_Group *grpBoot;
extern Fl_Browser *brwBootRef;
#include <FL/Fl_Input.H>
extern Fl_Input *options;
extern Fl_Group *grpReview;
extern Fl_Browser *brwReview;
#include <FL/Fl_Button.H>
extern Fl_Button *btnProceed;
extern Fl_Group *grpButtons;
#endif
