// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef mousetool_h
#define mousetool_h
#include <FL/Fl.H>
void dial_callback(Fl_Widget*, void*);
void btn_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Dial.H>
extern Fl_Dial *dial_speed;
#include <FL/Fl_Box.H>
extern Fl_Box *box_speed;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *btn_right;
extern Fl_Round_Button *btn_left;
#include <FL/Fl_Button.H>
#endif
