// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef exittc_h
#define exittc_h
#include <FL/Fl.H>
void btn_callback(Fl_Widget*, void*userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *device_output;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btn_backup;
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#endif
