// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include <libintl.h>
#include "add2file.h"
// (c) Robert Shingledecker 2008
#include <iostream>
#include <fstream>
#include <string>
#include <FL/Fl_File_Chooser.H>
using namespace std;
#include <locale.h>

int main(int argc, char **argv) {
  // Can't edit int main(int, char**) through fluid.
  argc = argc;
  
  if (argv[1] == NULL )
     exit(1);
  
  setlocale(LC_ALL, "");
  bindtextdomain("tinycore","/usr/local/share/locale");
  textdomain("tinycore");
  
  string filename = argv[1];
  string title = gettext("Select File to be added to ");
  title = title + filename;
  Fl_File_Chooser chooser(".","*", Fl_File_Chooser::SINGLE, title.c_str());
  chooser.show();                                             
  while(chooser.shown())
    { Fl::wait(); }
    
  if ( chooser.value() == NULL )
     exit(1); 
   
  ofstream fout(filename.c_str(), ios::out | ios::app);
  if (! fout.is_open())
  {
     cerr << "Can't open " << filename << " file for output." << endl;
     exit(EXIT_FAILURE);
  }
  fout << chooser.value()+1 << endl;
  fout.close();
  return Fl::run();
}
