// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "add2file.h"
// (c) Robert Shingledecker 2008
#include <iostream>
#include <fstream>
#include <string>
#include <FL/Fl_File_Chooser.H>
using namespace std;

int main(int argc, char **argv) {
  if (argv[1] == NULL )
   exit(1);
   
string filename = argv[1];
string title = "Select File to be added to " + filename;
Fl_File_Chooser chooser(".","*", Fl_File_Chooser::SINGLE, title.c_str());
chooser.show();                                             
while(chooser.shown())
  { Fl::wait(); }
  
if ( chooser.value() == NULL )
   exit(1); 
 
ofstream fout(filename.c_str(), ios::out | ios::app);
if (! fout.is_open())
{
   cerr << "Can't open " << filename << " file for output." << endl;
   exit(EXIT_FAILURE);
}
fout << chooser.value()+1 << endl;
fout.close();
  return Fl::run();
}
