// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef services_h
#define services_h
#include <FL/Fl.H>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Pack.H>
#endif
