// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include <libintl.h>
#include "flpdf.h"
// (c) Robert Shingledecker 2011
#include <cstdlib>
#include <iostream>
#include <fstream>
#include <string>
#include <FL/Fl_File_Chooser.H>
using namespace std;
#include <locale.h>

int main(int argc, char **argv) {
  setlocale(LC_ALL, "");
bindtextdomain("tinycore","/usr/local/share/locale");
textdomain("tinycore");

string title = gettext("Select PDF File to view with mupdf: ");
Fl_File_Chooser chooser(".","*.pdf", Fl_File_Chooser::SINGLE, title.c_str());
chooser.show();                                             
while(chooser.shown())
  { Fl::wait(); }
  
if ( chooser.value() == NULL )
   exit(1); 
 
string filename = chooser.value(); 
string command = "mupdf " + filename +" &";
cout << command.c_str() << endl;
system(command.c_str());
exit(0);
  return Fl::run();
}
