// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef filechooser_h
#define filechooser_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Help_View.H>
#endif
