// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "filechooser.h"

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(395, 255);
    w = o;
    { new Fl_Help_View(25, 25, 350, 210);
    } // Fl_Help_View* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
