// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include <libintl.h>
#include "loadpack.h"
// (c) Robert Shingledecker 2011
#include <iostream>
#include <fstream>
#include <string>
#include <FL/Fl_File_Chooser.H>
#include <FL/fl_message.H>
using namespace std;
#include <locale.h>
static string command, msg; 

int main(int argc, char **argv) {
  setlocale(LC_ALL, "");
bindtextdomain("tinycore","/usr/local/share/locale");
textdomain("tinycore");

string title = gettext("Navigate to and Select Starter Pack to load.");
Fl_File_Chooser chooser("/mnt","*.gz", Fl_File_Chooser::SINGLE, title.c_str());
chooser.show();                                             
while(chooser.shown())
  { Fl::wait(); }
  
if ( chooser.value() == NULL )
   exit(1); 
 
cout << chooser.value()+1 << endl;

string prepack = chooser.value()+1;
// command = "cd / &&  zcat '" + prepack + "' | sudo cpio -idmu";
command="sudo loadpack.sh '" + prepack + "'";
int results = system(command.c_str());
if ( results == 0 ) {
/*
   system("sudo /sbin/depmod -a 2>/dev/null");
   system("sudo /sbin/udevadm trigger");
   system("sudo /sbin/ldconfig");
   */
   msg = prepack + " successfully loaded.";
   fl_message(msg.c_str());
}
  return Fl::run();
}
