// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "flrun.h"
// (c) Robert Shingledecker 2008
#include <iostream>
#include <string>
#include <FL/Fl_File_Chooser.H>
using namespace std;

void btn_callback(Fl_Widget*, void* userdata) {
  if (userdata == "ok")
{
  string commandStr1 = in_command->value();
  string commandStr2 = " 2>/dev/null &";
  string command = commandStr1 + commandStr2;
  system(command.c_str());
  exit(0);
} else { 
  if (userdata == "cancel") 
  {
    exit(0);
  }
}
}

void choose_cb(Fl_Widget*, void*) {
  Fl_File_Chooser chooser(".",                        // directory
                            "*",                        // filter
                            Fl_File_Chooser::SINGLE,     // chooser type
                            "Select Application to Run");  // title
    chooser.show();                                             

    // Block until user picks something.
    //     (The other way to do this is to use a callback())
    //                                                      
    while(chooser.shown())
        { Fl::wait(); }

    // User hit cancel?
    if ( chooser.value() == NULL )
       return; 
 
    in_command->value(chooser.value());
}

Fl_Input *in_command=(Fl_Input *)0;

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(260, 100, "flrun");
    w = o;
    { Fl_Box* o = new Fl_Box(15, 25, 215, 0, "Application Launcher");
      o->align(FL_ALIGN_TOP);
    } // Fl_Box* o
    { in_command = new Fl_Input(25, 31, 215, 24);
      in_command->labeltype(FL_NO_LABEL);
    } // Fl_Input* in_command
    { Fl_Return_Button* o = new Fl_Return_Button(25, 65, 66, 20, "OK");
      o->callback((Fl_Callback*)btn_callback, (void*)("ok"));
    } // Fl_Return_Button* o
    { Fl_Button* o = new Fl_Button(100, 65, 64, 20, "&Cancel");
      o->callback((Fl_Callback*)btn_callback, (void*)("cancel"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(175, 65, 64, 20, "Browse");
      o->callback((Fl_Callback*)choose_cb);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
