// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef flrun_h
#define flrun_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Input_Choice.H>
extern Fl_Input_Choice *in_command;
#include <FL/Fl_Check_Button.H>
#endif
