// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef wbar_exclude_h
#define wbar_exclude_h
#include <FL/Fl.H>
void brw_onboot_callback(Fl_Widget *, void *);
void brw_wbar_callback(Fl_Widget *, void *);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brw_onboot;
extern Fl_Browser *brw_wbar;
#endif
