// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef datetool_h
#define datetool_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *yearInput;
#include <FL/Fl_Button.H>
extern Fl_Input *monthInput;
extern Fl_Input *dayInput;
extern Fl_Input *hourInput;
extern Fl_Input *minInput;
#endif
