// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef scmapps_h
#define scmapps_h
#include <FL/Fl.H>
void fetch_extension();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *errwindow;
#include <FL/Fl_Box.H>
extern Fl_Box *errlabel;
#include <FL/Fl_Button.H>
void brwMultiCB(Fl_Widget *, void *);
void btnMultiCB(Fl_Widget *, void *);
void brwResultsCB(Fl_Widget *, void *);
extern Fl_Double_Window *window;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menuBar;
extern void menuCB(Fl_Menu_*, void*);
extern void btnMirrorCB(Fl_Menu_*, void*);
#include <FL/Fl_Group.H>
extern Fl_Group *grpSearch;
#include <FL/Fl_Choice.H>
extern Fl_Choice *choiceSearch;
#include <FL/Fl_Input.H>
extern Fl_Input *search_field;
extern Fl_Box *boxLeftSide;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brwExtensions;
extern Fl_Group *grpUpdates;
extern Fl_Browser *brwMulti;
extern Fl_Button *btnMulti;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs;
extern Fl_Group *infoTab;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *infoDisplay;
extern Fl_Group *filesTab;
extern Fl_Text_Display *filesDisplay;
extern Fl_Group *dependsTab;
extern Fl_Text_Display *dependsDisplay;
extern Fl_Group *grpResults;
extern Fl_Box *boxResults;
extern Fl_Browser *brwResults;
extern Fl_Group *grpInstall;
extern Fl_Choice *choiceInstall;
extern Fl_Button *btnGo;
#include <FL/Fl_Output.H>
extern Fl_Output *outputStatus;
extern Fl_Button *btn_tce;
extern Fl_Output *uri;
extern Fl_Menu_Item menu_menuBar[];
#define scmapps (menu_menuBar+0)
extern Fl_Menu_Item menu_choiceSearch[];
extern Fl_Menu_Item menu_choiceInstall[];
#endif
