// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef cpanel_h
#define cpanel_h
#include <FL/Fl.H>
void btn_callback(Fl_Widget* w, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
extern Fl_Light_Button *tftpd;
extern Fl_Light_Button *ssh;
extern Fl_Light_Button *dhcpc;
extern Fl_Light_Button *crond;
#endif
