// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include "cpanel.h"
// (c) Robert Shingledecker 2008-2010
#include <iostream>
using namespace std;

void btn_callback(Fl_Widget* w, void* userdata) {
  system((const char*)userdata);
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(405, 215);
    w = o;
    { Fl_Button* o = new Fl_Button(10, 10, 120, 30, "Apps Audit");
      o->callback((Fl_Callback*)btn_callback, (void*)("appsaudit &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(140, 10, 120, 30, "Backup/Restore");
      o->callback((Fl_Callback*)btn_callback, (void*)("filetool &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 10, 120, 30, "Mount Tool");
      o->callback((Fl_Callback*)btn_callback, (void*)("mnttool &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 50, 120, 30, "Date/Time");
      o->callback((Fl_Callback*)btn_callback, (void*)("datetool &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(140, 50, 120, 30, "Wallpaper");
      o->callback((Fl_Callback*)btn_callback, (void*)("wallpaper &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 50, 120, 30, "Swapfile Tool");
      o->callback((Fl_Callback*)btn_callback, (void*)("swapfile &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 90, 120, 30, "Set TCE Drive");
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm +tr +sb -e tce-setdrive &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(140, 90, 120, 30, "Network");
      o->callback((Fl_Callback*)btn_callback, (void*)("sudo network &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 90, 120, 30, "Xvesa Setup");
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm +tr +sb -e xsetup.sh &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 130, 120, 30, "Floppy Tool");
      o->callback((Fl_Callback*)btn_callback, (void*)("fdtool&"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(140, 130, 120, 30, "Mouse Tool");
      o->callback((Fl_Callback*)btn_callback, (void*)("mousetool &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 130, 120, 30, "System Stats");
      o->callback((Fl_Callback*)btn_callback, (void*)("stats &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(10, 170, 120, 30, "Update Apps");
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm +tr +sb -e tce-update &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(140, 170, 120, 30, "USB Install");
      o->callback((Fl_Callback*)btn_callback, (void*)("aterm +tr +sb -e sudo usbinstall &"));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(270, 170, 120, 30, "Run Command");
      o->callback((Fl_Callback*)btn_callback, (void*)("flrun &"));
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  w->show(argc, argv);
  return Fl::run();
}
