// generated by Fast Light User Interface Designer (fluid) version 1.0110

#include <libintl.h>
#include "mirrorpicker.h"
#include "other.h"

Fl_Double_Window *win=(Fl_Double_Window *)0;

Fl_Progress *prog=(Fl_Progress *)0;

Fl_Box *lbl=(Fl_Box *)0;

Fl_Button *okbtn=(Fl_Button *)0;

static void cb_okbtn(Fl_Button*, void*) {
  accept();
}

Fl_Button *cancelbtn=(Fl_Button *)0;

static void cb_cancelbtn(Fl_Button*, void*) {
  exit(0);
}

int main(int argc, char **argv) {
  setlocale(LC_ALL, "");
bindtextdomain("tinycore","/usr/local/share/locale");
textdomain("tinycore");
  { win = new Fl_Double_Window(265, 165, gettext("Mirror picker"));
    { prog = new Fl_Progress(25, 20, 215, 25);
      prog->selection_color((Fl_Color)58);
    } // Fl_Progress* prog
    { lbl = new Fl_Box(25, 55, 215, 45);
      lbl->align(FL_ALIGN_WRAP);
    } // Fl_Box* lbl
    { okbtn = new Fl_Button(30, 110, 90, 35, gettext("OK"));
      okbtn->callback((Fl_Callback*)cb_okbtn);
      okbtn->deactivate();
    } // Fl_Button* okbtn
    { cancelbtn = new Fl_Button(145, 110, 90, 35, gettext("Cancel"));
      cancelbtn->callback((Fl_Callback*)cb_cancelbtn);
    } // Fl_Button* cancelbtn
    win->end();
  } // Fl_Double_Window* win
  init(argc, argv);
  win->show(argc, argv);
  return Fl::run();
}
