// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef mirrorpicker_h
#define mirrorpicker_h
#include <FL/Fl.H>
#include <locale.h>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Progress.H>
extern Fl_Progress *prog;
#include <FL/Fl_Box.H>
extern Fl_Box *lbl;
#include <FL/Fl_Button.H>
extern Fl_Button *okbtn;
extern Fl_Button *cancelbtn;
#endif
