// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "popask.h"
// (c) Robert Shingledecker
#include <iostream>
#include <string>
#include <Fl/fl_ask.H>
using namespace std;

int main(int argc, char **argv) {
  string msg;
for (int i=1; i < argc; i++)
   msg = msg + argv[i] + " ";
cout << fl_ask(msg.c_str()) << endl;
  return Fl::run();
}
