// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include "popask.h"
// (c) Robert Shingledecker
#include <iostream>
#include <string>
#include <FL/fl_ask.H>
using namespace std;

int main(int argc, char **argv) {
  string msg;
  for (int i=1; i < argc; i++)
     msg = msg + argv[i] + " ";
  cout << fl_choice(msg.c_str(), "No", "Yes", NULL) << endl;
  return Fl::run();
}
