// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef filetool_h
#define filetool_h
#include <FL/Fl.H>
void input_callback(Fl_Widget*, void*);
void btn_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Input.H>
extern Fl_Input *input_device;
#include <FL/Fl_Choice.H>
extern Fl_Choice *filetool_choice;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_go;
extern Fl_Menu_Item menu_filetool_choice[];
#endif
