// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef filetool_h
#define filetool_h
#include <FL/Fl.H>
void input_callback(Fl_Widget*, void*);
void btn_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
extern Fl_Input *input_device;
#include <FL/Fl_Button.H>
extern Fl_Button *btn_none;
extern Fl_Button *btn_backup;
extern Fl_Button *btn_restore;
#endif
