// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef apps_h
#define apps_h
#include <FL/Fl.H>
void protectChr();
void displayTabData();
void loadBrwExtnData();
void loadBrwResultsData();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *errwindow;
#include <FL/Fl_Box.H>
extern Fl_Box *errlabel;
#include <FL/Fl_Button.H>
void dependsCB(Fl_Widget *, void* userdata);
void brwExtnCB(Fl_Widget *, void *);
void btnSingleCB(Fl_Widget *, void *);
void brwMultiCB(Fl_Widget *, void *);
void btnMultiCB(Fl_Widget *, void *);
void brwResultsCB(Fl_Widget *, void *);
void btnResultsCB(Fl_Widget *, void *);
void mirrorpicker();
extern Fl_Double_Window *window;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Bar *menuBarApps;
extern void menuCB(Fl_Menu_*, void*);
extern void mirrorCB(Fl_Menu_*, void*);
extern Fl_Menu_Bar *menuBarDepends;
extern void dependsCB(Fl_Menu_*, void*);
#include <FL/Fl_Group.H>
extern Fl_Group *resizeVictim;
extern Fl_Group *grpBrowse;
extern Fl_Group *grpSearch;
#include <FL/Fl_Choice.H>
extern Fl_Choice *search_choices;
#include <FL/Fl_Input.H>
extern Fl_Input *search_field;
extern Fl_Box *boxSelect;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brwSelect;
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs;
extern Fl_Group *infoTab;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *infoDisplay;
extern Fl_Group *filesTab;
extern Fl_Text_Display *filesDisplay;
extern Fl_Group *dependsTab;
extern Fl_Text_Display *dependsDisplay;
extern Fl_Group *sizeTab;
extern Fl_Text_Display *sizeDisplay;
extern Fl_Choice *install_choices;
extern Fl_Button *btnGo;
#include <FL/Fl_Output.H>
extern Fl_Output *outputStatus;
extern Fl_Button *btn_tce;
extern Fl_Output *outURI;
extern Fl_Group *grpAudit;
extern Fl_Box *boxExtn;
extern Fl_Group *grpSingle;
extern Fl_Browser *brwExtn;
extern Fl_Button *btnSingle;
extern Fl_Box *boxResults;
extern Fl_Group *grpMulti;
extern Fl_Browser *brwMulti;
extern Fl_Button *btnMulti;
extern Fl_Browser *brwResults;
extern Fl_Button *btnResults;
extern Fl_Output *outTCE;
extern Fl_Menu_Item menu_menuBarApps[];
#define menuApps (menu_menuBarApps+0)
extern Fl_Menu_Item menu_menuBarDepends[];
#define menu_auditall (menu_menuBarDepends+3)
#define menu_fetchmissing (menu_menuBarDepends+4)
#define menu_nodepends (menu_menuBarDepends+5)
#define menu_notrequired (menu_menuBarDepends+6)
#define menu_dependson (menu_menuBarDepends+7)
#define menu_requiredby (menu_menuBarDepends+8)
#define menu_missing (menu_menuBarDepends+9)
#define menu_delete (menu_menuBarDepends+10)
#define menu_marked (menu_menuBarDepends+11)
#define menu_clearlst (menu_menuBarDepends+12)
extern Fl_Menu_Item menu_search_choices[];
extern Fl_Menu_Item menu_install_choices[];
#endif
