// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef mnttool_h
#define mnttool_h
#include <FL/Fl.H>
int getMountables();
void btnCallback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btnDevice;
extern Fl_Button *btnState;
#endif
