// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef mnttool_h
#define mnttool_h
#include <FL/Fl.H>
int getMountables();
void btnCallback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *w;
#include <FL/Fl_Pack.H>
extern Fl_Pack *pack;
#endif
