// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef fdtool_h
#define fdtool_h
#include <FL/Fl.H>
void btnCallback(Fl_Widget*, void* userdata);
void inp_callback(Fl_Widget*, void*);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *btn1440;
extern Fl_Round_Button *btn1722;
#include <FL/Fl_Input.H>
extern Fl_Input *inpImagePath;
#include <FL/Fl_Button.H>
extern Fl_Button *btnMkImage;
extern Fl_Button *btnApImage;
#endif
