// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef wallpaper_h
#define wallpaper_h
#include <FL/Fl.H>
void imageBrowserCallback(Fl_Widget*, void*);
void btnCallback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *imageBrowser;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *btnScale;
extern Fl_Round_Button *btnTile;
#include <FL/Fl_Button.H>
extern Fl_Button *installBtn;
#endif
