// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef stats_h
#define stats_h
#include <FL/Fl.H>
void tabsGroupCB(Fl_Widget*, void*userdata);
void tabCB(Fl_Widget*, void*userdata);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
extern Fl_Tabs *tabs;
#include <FL/Fl_Group.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *cpuDisplay;
extern Fl_Text_Display *memDisplay;
extern Fl_Text_Display *netDisplay;
extern Fl_Text_Display *modulesDisplay;
extern Fl_Text_Display *processesDisplay;
extern Fl_Text_Display *dmesgDisplay;
extern Fl_Text_Display *mountsDisplay;
extern Fl_Text_Display *filesystemsDisplay;
extern Fl_Text_Display *bootDisplay;
extern Fl_Text_Display *extensionsDisplay;
extern Fl_Text_Display *bigDisplay;
#endif
