// generated by Fast Light User Interface Designer (fluid) version 1.0109

#ifndef stats_h
#define stats_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *cpuBrowser;
extern Fl_Browser *memBrowser;
extern Fl_Browser *netBrowser;
extern Fl_Browser *modulesBrowser;
extern Fl_Browser *pciBrowser;
extern Fl_Browser *processesBrowser;
extern Fl_Browser *dmesgBrowser;
extern Fl_Browser *mountsBrowser;
extern Fl_Browser *filesystemsBrowser;
extern Fl_Browser *bootBrowser;
extern Fl_Browser *extensionsBrowser;
#endif
