// generated by Fast Light User Interface Designer (fluid) version 1.0109

#include "popup.h"
// (c) Robert Shingledecker 2008
#include <iostream>
#include <FL/fl_message.H>
#include <string>
using namespace std;

int main(int argc, char **argv) {
  string msg;
for (int i=1; i < argc; i++)
   msg = msg + argv[i] + " ";
fl_message(msg.c_str());
  return Fl::run();
}
