// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef tc_install_h
#define tc_install_h
#include <FL/Fl.H>
#include <unistd.h>
void selectFile();
void prepTarget();
void cursor_normal();
void cursor_wait();
void btnCB(Fl_Widget*, void*userdata);
void brwCB(Fl_Widget*, void*userdata);
void btnProceedCB(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *window;
#include <FL/Fl_Wizard.H>
extern Fl_Wizard *wWizard;
#include <FL/Fl_Group.H>
extern Fl_Group *grpType;
#include <FL/Fl_Box.H>
extern Fl_Box *lblPathCore;
#include <FL/Fl_Output.H>
extern Fl_Output *fullpathOutput;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *btnWhole;
extern Fl_Check_Button *btnPartition;
#include <FL/Fl_Browser.H>
extern Fl_Browser *brwTarget;
extern Fl_Check_Button *btnActive;
extern Fl_Check_Button *btnBootloader;
extern Fl_Group *grpFormat;
extern Fl_Group *FormatType;
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *btnNoFormat;
extern Fl_Round_Button *btnExt2Format;
extern Fl_Round_Button *btnExt3Format;
extern Fl_Round_Button *btnExt4Format;
extern Fl_Round_Button *btnVfatFormat;
extern Fl_Group *grpBoot;
extern Fl_Browser *brwBootRef;
#include <FL/Fl_Input.H>
extern Fl_Input *options;
extern Fl_Group *grpExtensionsCorePlus;
extern Fl_Group *installType;
extern Fl_Round_Button *installCoreX11;
extern Fl_Round_Button *installCoreOnly;
extern Fl_Group *corePlusExtensions;
extern Fl_Check_Button *btnWifi;
extern Fl_Check_Button *btnNdiswrapper;
extern Fl_Check_Button *btnWifiFirmware;
extern Fl_Check_Button *btnInstaller;
extern Fl_Check_Button *btnRemaster;
extern Fl_Check_Button *btnKmaps;
extern Fl_Group *grpExtensionsStandAlone;
extern Fl_Round_Button *btnInstallExtensions;
extern Fl_Round_Button *btnNoExtensions;
extern Fl_Output *outputTCEDir;
extern Fl_Group *grpReview;
extern Fl_Browser *brwReview;
#include <FL/Fl_Button.H>
extern Fl_Button *btnProceed;
extern Fl_Group *grpButtons;
#endif
